name: Spring CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install
      - name: Test with Maven
        run: mvn test
      - name: Check test results and exit on failure
        run: |
         if [ ${{ job.status }} == 'failure' ]; then
           echo "Tests failed. Exiting the workflow."
           exit 1
         fi
#      - name: Docker login
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Run Maven Build
#        if: success()
#        run: mvn clean compile jib:build

        





